# Generated by Django 5.0.1 on 2024-04-12 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_clubresponse_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Secondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(default='null', max_length=100)),
                ('notifications_clubmeets', models.TextField()),
                ('qr_code_data', models.CharField(blank=True, max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notification_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='club_primary',
            name='qr_code_data',
        ),
        migrations.AddField(
            model_name='club_primary',
            name='brief_info',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='club_primary',
            name='contacts',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='club_primary',
            name='events',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='club_primary',
            name='links',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='club_primary',
            name='highlights',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='club_primary',
            name='motto',
            field=models.TextField(default='null'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubs', models.ManyToManyField(to='base.club_secondary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
