# Generated by Django 5.0.1 on 2024-04-12 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_club_secondary_remove_club_primary_qr_code_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club_secondary',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applied_to_clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
