# Generated by Django 5.0.1 on 2024-04-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_club_secondary_inductees_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='null')),
                ('password', models.TextField(default='null')),
            ],
        ),
    ]
